# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=50),
        ),
    ]
