# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20171021_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='items',
            field=models.ManyToManyField(to='store.Item', verbose_name='bucket_items'),
        ),
    ]
