# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20171021_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='items',
        ),
        migrations.AddField(
            model_name='bucket',
            name='items',
            field=models.TextField(default=''),
        ),
    ]
